### ISSUE TITLE
@Transactional not working after migration to SpringTestExtension

### ISSUE THREAD

**Issue by codymikol** [kotest/kotest-extensions-spring#24]
When using SpringListener for our @SpringBootTest tests, we were able to annotate the class as @Transactional and it wrapped  describes in a transaction, rolling back between each suite. after migrating to SpringTestExtension, this no longer seems to work.

**Comment by hanqyu** [comment]
For me, using SpringTestExtension like
```kotlin
override fun extensions(): List<Extension> = listOf(SpringTestExtension(SpringTestLifecycleMode.Root))
```
was helpful.

Default parameter is `SpringTestLifecycleMode.Test`

**Comment by codymikol** [comment]
This is the solution for sure ^^
