### ISSUE TITLE
nightly/snapshot release problems

### ISSUE THREAD

**Issue by FyiurAmron** [kotest/kotest-extensions-spring#81]
First, since the snapshot branch is versioned as 1.1.0.buildNr-SNAPSHOT, using it will make dep update tools (like Renovate) go bonkers since they will believe that 1.1.2 is later and that e.g. 1.1.0.75-SNAPSHOT should be updated to 1.1.2; I'd say that snapshot branch versioning should follow actual versioning, so after e.g. 1.1.2 release all later snapshots should be 1.1.3-buildNr etc. since in Java ecosystem SNAPSHOT is a pre-release versioning (as per https://stackoverflow.com/questions/5901378/what-exactly-is-a-maven-snapshot-and-why-do-we-need-it ) ; alternatively, you can argue it's just a build of 1.1.2, and name it 1.1.2 if you find that more sensible, but, for the sake of it, don't call it 1.1.0.buildNr-SNAPSHOT anymore :D

Second, I (and probably I'm not the only one) would be really glad to see an actual 1.1.3 release, since it's been a while from 1.1.2, and  even if the updates have been only dep updates and other chores, it would still be great to see a maintenance release every now and then.

Thirdly, https://s01.oss.sonatype.org/ was down today extensively, which is yet-another-reason I think a stable release with maintenance updates would be nice from time to time (since maven mirrors for stable releases are, well, more stable and ubiquitous)

**Comment by FyiurAmron** [comment]
@Kantis

**Comment by Kantis** [comment]
I agree, we should get a 1.1.3 maintenance release out, and possibly 2.0 for Spring Boot 3 / Kotest 5.6 / Kotlin 1.8

**Comment by Kantis** [comment]
1.1.3 on the way out. 

I believe a consuming project can use 1.1.3 and still use Kotest 5.6, Kotlin 1.8 and Spring Boot 3, so might hold off on v2 for a while.
